FROM jupyter/datascience-notebook

RUN conda update -n base conda
RUN conda install theano
RUN conda install pymc3
RUN conda install pip
RUN conda install mkl-service
RUN conda install -c conda-forge jupyter_contrib_nbextensions

